export type AuthUser = {
    aud: string,
    auth_time: number,
    "cognito:username": string,
    email: string,
    email_verified: true,
    event_id: string,
    exp: number,
    iat: number,
    iss: string,
    jti: string,
    origin_jti: string,
    sub: string,
    token_use: string,
}